# Valve configuration for different step types
# Valve numbers correspond to:
# 1: Gas 1 valve
# 2: Gas 2 valve
# 3: Inlet valve
# 4: Outlet valve
# 5: Slow Vent valve
# 6: Quick Vent valve

# Valve states:
# - open: Explicitly open the valve
# - close: Explicitly close the valve
# - ignore: Maintain current valve state

step_types:
  pressurize:
    type: 'p'
    valves:
      1: ignore
      2: ignore
      3: open
      4: close
      5: close
      6: close

  bubble:
    type: 'b'
    valves:
      1: ignore
      2: ignore
      3: open    # Open inlet valve
      4: open    # Open outlet valve
      5: open    # Open slow vent valve
      6: close    # Close quick vent valve

  slow vent:
    type: 'v'
    valves:
      1: ignore
      2: ignore
      3: close
      4: open
      5: close
      6: open    # Open vent valve

  quick vent:
    type: 'q'
    valves:
      1: ignore
      2: ignore
      3: close
      4: open
      5: close   # Open short valve
      6: open    # Open vent valve

  close:
    type: 'c'
    valves:
      1: close
      2: close
      3: close
      4: close
      5: close
      6: close

  wait:
    type: 'w'
    valves:
      1: ignore
      2: ignore
      3: ignore
      4: ignore
      5: ignore
      6: ignore 
  
  default:
    type: 'f'
    valves:
      1: ignore
      2: ignore
      3: close
      4: close
      5: close
      6: close

  set gas ph2:
    type: 'g'
    valves:
      1: close
      2: close
      3: ignore
      4: ignore
      5: ignore
      6: ignore

  set gas h2:
    type: 'h'
    valves:
      1: close
      2: open
      3: ignore
      4: ignore
      5: ignore
      6: ignore

  set gas n2:
    type: 'n'
    valves:
      1: open
      2: close
      3: ignore
      4: ignore
      5: ignore
      6: ignore 